# Generated by Django 2.0.4 on 2018-04-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0002_auto_20180430_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='course',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
