# Generated by Django 2.0.4 on 2018-04-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0004_auto_20180430_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='school',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='job',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
