# Generated by Django 2.0.4 on 2018-04-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0006_interests_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interests',
            new_name='Interest',
        ),
    ]
